DROP TABLE IF EXISTS rating CASCADE;
CREATE TABLE IF NOT EXISTS rating (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS film CASCADE;
CREATE TABLE IF NOT EXISTS film (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200),
    releaseDate date CHECK (releaseDate >= '1895-12-28'),
    duration integer CHECK (duration > 0),
    rating_id integer REFERENCES rating
);

DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE IF NOT EXISTS genre (
    genre_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS film_genre CASCADE;
CREATE TABLE IF NOT EXISTS film_genre (
    genre_id integer REFERENCES genre (genre_id) ON DELETE CASCADE,
    film_id integer REFERENCES film (film_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE IF NOT EXISTS users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    email varchar(40) NOT NULL,
    login varchar(40) NOT NULL,
    birthday date CHECK (birthday <= CURRENT_DATE)
);

DROP TABLE IF EXISTS likes CASCADE;
CREATE TABLE IF NOT EXISTS likes (
    user_id integer REFERENCES users (user_id) ON DELETE CASCADE,
    film_id integer REFERENCES film (film_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

DROP TABLE IF EXISTS friends CASCADE;
CREATE TABLE IF NOT EXISTS friends (
    user_id integer REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id integer,
    PRIMARY KEY (user_id, friend_id)
);

-- отзывы
CREATE TABLE IF NOT EXISTS reviews (
    review_id integer AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    is_positive BOOLEAN NOT NULL,
    user_id integer NOT NULL,
    film_id integer NOT NULL,
    useful integer DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES film(film_id) ON DELETE CASCADE,
    CONSTRAINT unique_user_film_review UNIQUE (user_id, film_id)
);

-- лайки/дизлайки отзывам
CREATE TABLE IF NOT EXISTS review_likes (
    review_id integer NOT NULL,
    user_id integer NOT NULL,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id),
    FOREIGN KEY (review_id) REFERENCES reviews(review_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS directors CASCADE;
CREATE TABLE IF NOT EXISTS directors (
    director_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL
);

DROP TABLE IF EXISTS film_director CASCADE;
CREATE TABLE IF NOT EXISTS film_director (
    director_id integer REFERENCES directors (director_id) ON DELETE CASCADE,
    film_id integer REFERENCES film (film_id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS events (
    event_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp timestamp NOT NULL,
    user_id integer NOT NULL,
    event_type varchar(20) NOT NULL,
    operation varchar(20) NOT NULL,
    entity_id integer NOT NULL,
    CONSTRAINT EVENTS_USER_FK FOREIGN KEY (user_id)
            REFERENCES users(user_id) ON DELETE CASCADE
);

