CREATE TABLE IF NOT EXISTS rating (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film (
    film_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    description varchar(200),
    releaseDate date CHECK (releaseDate >= '1895-12-28'),
    duration integer CHECK (duration > 0),
    rating_id integer REFERENCES rating
);

CREATE TABLE IF NOT EXISTS genre (
    genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genre (
    genre_id integer REFERENCES genre (genre_id) ON DELETE CASCADE,
    film_id integer REFERENCES film (film_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40),
    email varchar(40) NOT NULL,
    login varchar(40) NOT NULL,
    birthday date CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS likes (
    user_id integer REFERENCES users (user_id) ON DELETE CASCADE,
    film_id integer REFERENCES film (film_id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, film_id)
);

CREATE TABLE IF NOT EXISTS friends (
    user1_id integer REFERENCES users (user_id) ON DELETE CASCADE,
    user2_id integer REFERENCES users (user_id) ON DELETE CASCADE
);
